DROP TABLE IF EXISTS PUBLIC.FACT_MONTHLY_AIR_DATA;
CREATE TABLE PUBLIC.FACT_MONTHLY_AIR_DATA AS(
  SELECT
    *,
    NOW() AT TIME ZONE 'EST' AS last_inserted
  FROM(
      SELECT *
   , ROW_NUMBER() OVER(PARTITION BY "the_date","hours_utc" ORDER BY hours_utc DESC) AS RN
      FROM STAGE.stg_monthly_air_data
  ) A WHERE RN=1);